sentence  = input("Enter your sentence : ")
print("Your sentence is : "+ sentence)
word1 = input("Entre the qword to replace : ")
word2 = input("Entre the word to replace it with : ")
print(sentence.replace(word1,word2))